### ISSUE TITLE
Добавить readme.md, убрать из git папку idea, добавить checkstyle

### ISSUE THREAD

**Issue by ibobrov** [ScathiesGit/Currency-exchange#1]
https://gist.github.com/ibobrov/6c6cac95f71abd3a3ca4f4df28bd7650

**Comment by ScathiesGit** [comment]
https://github.com/ScathiesGit/Currency-exchange/tree/63fc0765755ba1a2d065b21c0fd2a738d2fcb74e

случайно запушил checkstyle.xml, забыв закинуть его в gitignore, но я уже убрал его, правда не в этом коммите, а через несколько

**Comment by ibobrov** [comment]
Хорошо, но файл checkstyle.xml должен быть в репозитории - возврщай.
