### ISSUE TITLE
Написание dao и тестов

### ISSUE THREAD

**Issue by ibobrov** [ScathiesGit/Currency-exchange#2]
1. Для начала тыкнешь на "alt" + "enter" на "JdbcCurrencyRepository", пусть идея сделает нужные папки, чтобы тебе этим не заниматься. 
![image](https://github.com/ScathiesGit/Currency-exchange/assets/30261348/ec917d25-82ff-4b51-b847-927b200ebc90)
2. У тебя будет вот так выглядить новый класс. Пакет в котором он лежит repository, и имя его тоже что у класса, с припиской test. Нам это и надо, в дальнейшем все тесты должны также называться - по имени тестируемого класса + в том же пакете.
![image](https://github.com/ScathiesGit/Currency-exchange/assets/30261348/02b747eb-74c5-4c20-8770-dafbe5ecc88a)
3. Я тебе написал тест, от него начнёшь, всё что не ясно будет спросишь.

```
package currency.exchange.api.repository;

import currency.exchange.api.model.Currency;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;


class JdbcCurrencyRepositoryTest {
    private final static CurrencyRepository currencyRepo = new JdbcCurrencyRepository();

    @BeforeAll
    public static void clean() throws Exception {
        currencyRepo
                .findAll()
                .forEach(
                        currency -> currencyRepo.delete(currency)
                );
    }

    @Test
    void whenSaveCurrencyThenFindById() throws Exception {
        var toSave = new Currency("code", "fullName", "sign");
        currencyRepo.save(toSave);
        assertThat(currencyRepo.findById(toSave.getId())).isEqualTo(toSave);
    }

}
```
В pom.xml надо поменять/добавить зависимости

```
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.9.2</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <version>5.9.2</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.23.1</version>
            <scope>test</scope>
        </dependency>
```

**Comment by ScathiesGit** [comment]
У меня проблемы с тестами. В целом я понимаю идею того, что должно получаться в итоге. Мы тестируем конкретные сценарии поведения метода
Давай я напишу что думаю насчет каждого метода и как его тестировать. Начну с того теста, который ты мне в качестве примера написал

save() тут нужно проверить, что метод сохраняет запись в базу данных. Мы заранее должны знать, что база данных не содержит такой записи, поэтому 
ты все удаляешь из нее в методе @BeforeAll clean(). Далее создаешь объект для сохранения, сохраняешь его. Теперь нужно проверить, что этот объект 
сохранился там, поэтому используешь метод findBy... и находишь эту запись. Далее сравниваешь созданный объект и полученный из метода findBy... 
и действительно, если они равны, то метод сохранил и ожидаемое поведение работает. Мы убедились, что записи не было в БД и убедились, что метод сохранил. 
Еще же есть второй сценарий работы этого метода, когда я пытаюсь сохранить запись, которая уже существует в БД, там исключение выброшено будет. Это же тоже нужно тестировать?

findAll() мне нужно проверить, что этот метод возвращает все записи из конкретной таблицы в БД. Тогда я должен знать все записи заранее, но как я могу их узнать?
Мне на ум ничего не приходит, кроме создания тестовой БД, далее занести туда список сущностей, вызвать метод findAll() и полученный список сравнить с тем, который
я хардкодом внес в тестовую БД. Также еще одна проблема возникает с тестом этого метода. Допустим я сделал тестовую БД и заполнил ее данными, но потом тот метод
clean(), который ты написал, все удаляет. Значит мне нужно убрать его и в методе save() создать запись, которую не содержит тестовая БД?

findByCurrencyIDs и update для них я написал тесты, не знаю насколько правильно конечно, но только для позитивного сценария правда

ссылка на коммит
https://github.com/ScathiesGit/Currency-exchange/commit/9783a64b597af53755a84ebb4a3de5d960551563

**Comment by ScathiesGit** [comment]
Сейчас почитал про транзакции, не буду редактировать предыдущий коммент. Я так полагаю нужно открывать @BeforeEach транзакцию, чистить БД и в @AfterEach ее откатывать? Тогда чтобы findAll() протестировать, я могу через save добавить несколько записей, потом вызвать findAll и сравнить размер списка с количеством добавленных записей и проверить на equals объекты списка и те объекты, что добавил через save?

**Comment by ibobrov** [comment]
Не понял как связаны транзакции и @ BeforeEach аннотация из JUnit (метод с этой аннатации зпускаестся либо до/после всех/каждого теста). Чтобы увидеть не покрытые места тестов ,не помешает смотреть покрытие тестов. В следующей задаче поставлю его добавление. Также поставлю задачу на рефакторинг, структуру проекта упростим, нам нужно меньше пакетов и классов - у нас простой пет-проект - будем писать проще.
