### ISSUE TITLE
Поменять полных путь, на относительный

### ISSUE THREAD

**Issue by ibobrov** [ScathiesGit/Currency-exchange#3]
https://github.com/ScathiesGit/Currency-exchange/blob/c4a75ec2d8c361cde3045e648784c3f9833123fb/src/main/resources/application.properties#L1

**Comment by ScathiesGit** [comment]
https://github.com/ScathiesGit/Currency-exchange/blob/5947a274d2fc740152564c917dc1c859b904d026/src/main/resources/application.properties#L1
https://github.com/ScathiesGit/Currency-exchange/blob/5947a274d2fc740152564c917dc1c859b904d026

**Comment by ibobrov** [comment]
Ок, хорошо
