### ISSUE TITLE
Попровить DAO, названия методов

### ISSUE THREAD

**Issue by ibobrov** [ScathiesGit/Currency-exchange#5]
Для нейминга используй следующий пулл имен:

- findAll
- findByCode
- findByCurrencyCode
- save
- update
- findById
- findBy...
- to... для перобразования ResultSet в модель

**Comment by ScathiesGit** [comment]
https://github.com/ScathiesGit/Currency-exchange/tree/6753922e5b9570913cbb68a39d8ebd925dfac48e

**Comment by ibobrov** [comment]
https://github.com/ScathiesGit/Currency-exchange/blob/6753922e5b9570913cbb68a39d8ebd925dfac48e/src/main/java/git/scathiesgit/dao/CurrencyDao.java#L17C1-L20C42
https://github.com/ScathiesGit/Currency-exchange/blob/6753922e5b9570913cbb68a39d8ebd925dfac48e/src/main/java/git/scathiesgit/dao/ExchangeRateDao.java#L26-L30

Вот это убираешь и из ResultSet берёшь через название поля (String), там можно и не по индексам.

**Comment by ibobrov** [comment]
Жду interface с описание методов findByCurrencyCodesOrCrossRate, findByCrossRateThroughUSD. Не ясно что за логика на уровне репозитория ,если в интерфейсе не будет ясно может созвонимся и вместе обсудим - пока выглядит как какое-то усложнение.
