### ISSUE TITLE
Поправить DAO, написать interface в котором основные методы dao

### ISSUE THREAD

**Issue by ibobrov** [ScathiesGit/Currency-exchange#6]
Напиши интерфейс отдели служебную логику jdbc от логики dao. Нужн чёткий интерфейс что даёт дао.

**Comment by ScathiesGit** [comment]
https://github.com/ScathiesGit/Currency-exchange/tree/bae62b7d5cfdb141f5872c18594b9a14e883fcaf

там есть методы findExchangeRate, findReverseRate, findUsdWithTarget они для поиска не самой записи ExchangeRate, а для курса вот по этому алгоритму:

    В таблице ExchangeRates существует валютная пара AB - берём её курс
    В таблице ExchangeRates существует валютная пара BA - берем её курс, и считаем обратный, чтобы получить AB
    В таблице ExchangeRates существуют валютные пары USD-A и USD-B - вычисляем из этих курсов курс AB

Этими вещами приложение должно заниматься на уровне репозитория или сервис? Если сервис, то наверное можно их убрать и в сервисе делать вызов в репозиторий за прямым курсом, если его не будет, то за обратным, если и его не будет, то через доллар?

Я за эти дни много всяких реализаций сделал, но не очень получается сделать по-нормальному, всегда что-то не то по ощущениям

**Comment by ibobrov** [comment]
Хорошо, думаю так не плохо - убери только Dao. Два метода можно что внём можно и напрямую указать в интерфейсе.
