### ISSUE TITLE
Добавить jococo и получить аналогичный репорт как на скрине.

### ISSUE THREAD

**Issue by ibobrov** [ScathiesGit/Currency-exchange#8]
1) Добавляешь в pom.xml следующую зависимость:

```
<build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <version>3.1.2</version>
      ....
      </plugin>

      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.8.7</version>
        <executions>
          <execution>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>report</id>
            <phase>test</phase>
            <goals>
              <goal>report</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```
2) Делаешь в мавен package (в идеи справа мавен -> lifecycle). Затем переходишь в target -> site -> index.html -> open in -> browser
![image](https://github.com/ScathiesGit/Currency-exchange/assets/30261348/a3f166a8-ac9c-4338-a6fd-8db2baef5aae)
3) Смотришь отчёт, проваливаешся в классы. Красное не покрыто, желтоё покрыты не все условия.

**Comment by ScathiesGit** [comment]
тесты на репозиторий
https://github.com/ScathiesGit/Currency-exchange/commit/7155beffdb38c4264ef839a72e49fbe45514346b

**Comment by ScathiesGit** [comment]
сервисы
https://github.com/ScathiesGit/Currency-exchange/commit/9efd42c9c07d8cb16ed03ddc7f49b22d9f2e2607

**Comment by ScathiesGit** [comment]
jacoco + github actions
https://github.com/ScathiesGit/Currency-exchange/commit/29377cd0adb0dfa57f1383f1b4dcdb7d515ddb4a
